import type { Enum } from '@zenstackhq/language/ast'
import { extractEnumLabel, toTitleCase } from './parser.js'
import type { EnumInfo, I18nConfig } from './types.js'

/**
 * Extract enum information from AST.
 */
export function extractEnumInfo(enumDecl: Enum): EnumInfo {
  const values = enumDecl.fields.map((field) => {
    const label = extractEnumLabel(field.comments) ?? toTitleCase(field.name)
    return {
      name: field.name,
      label,
    }
  })

  return {
    name: enumDecl.name,
    values,
  }
}

/**
 * Generate code for an enum file.
 *
 * Produces:
 * - EnumFormSchema with .meta({ ui: { options: [...] } })
 * - EnumLabels lookup object
 */
export function generateEnumCode(enumInfo: EnumInfo, i18nConfig: I18nConfig | null = null): string {
  const { name, values } = enumInfo

  const enumValues = values.map((v) => `'${v.name}'`).join(', ')

  // Generate options with i18nKey when i18n is enabled
  const optionsArray = values
    .map((v) => {
      const parts = [`value: '${v.name}'`, `label: '${v.label}'`]
      if (i18nConfig?.enabled) {
        parts.push(`i18nKey: '${name}.${v.name}'`)
      }
      return `      { ${parts.join(', ')} }`
    })
    .join(',\n')

  const labelsObject = values.map((v) => `  ${v.name}: '${v.label}'`).join(',\n')

  return `// AUTO-GENERATED by @letar/zenstack-form-plugin
// DO NOT EDIT MANUALLY

import { z } from 'zod/v4'

/**
 * Zod schema for enum ${name} with UI metadata.
 */
export const ${name}FormSchema = z.enum([${enumValues}])
  .meta({
    ui: {
      options: [
${optionsArray}
      ]
    }
  })

/**
 * Labels for ${name} enum values.
 */
export const ${name}Labels = {
${labelsObject}
} as const

/**
 * Enum value type.
 */
export type ${name}Value = z.infer<typeof ${name}FormSchema>
`
}
