import type { Enum } from '@zenstackhq/language/ast'
import { extractEnumLabel, toTitleCase } from './parser.js'
import type { EnumInfo, I18nConfig } from './types.js'

/**
 * Извлечь информацию об enum из AST
 *
 * @param enumDecl Enum декларация из AST
 * @returns Информация об enum с метками
 */
export function extractEnumInfo(enumDecl: Enum): EnumInfo {
  const values = enumDecl.fields.map((field) => {
    const label = extractEnumLabel(field.comments) ?? toTitleCase(field.name)
    return {
      name: field.name,
      label,
    }
  })

  return {
    name: enumDecl.name,
    values,
  }
}

/**
 * Сгенерировать код для enum файла
 *
 * Генерирует:
 * - EnumFormSchema с .meta({ ui: { options: [...] } })
 * - EnumLabels объект для быстрого доступа
 *
 * @param enumInfo Информация об enum
 * @param i18nConfig Конфигурация i18n (опционально)
 * @returns Сгенерированный TypeScript код
 */
export function generateEnumCode(enumInfo: EnumInfo, i18nConfig: I18nConfig | null = null): string {
  const { name, values } = enumInfo

  const enumValues = values.map((v) => `'${v.name}'`).join(', ')

  // Генерируем options с i18nKey если i18n включен
  const optionsArray = values
    .map((v) => {
      const parts = [`value: '${v.name}'`, `label: '${v.label}'`]
      if (i18nConfig?.enabled) {
        parts.push(`i18nKey: '${name}.${v.name}'`)
      }
      return `      { ${parts.join(', ')} }`
    })
    .join(',\n')

  const labelsObject = values.map((v) => `  ${v.name}: '${v.label}'`).join(',\n')

  return `// AUTO-GENERATED by @lena/zenstack-form-plugin
// DO NOT EDIT MANUALLY

import { z } from 'zod/v4'

/**
 * Zod схема для enum ${name} с UI метаданными
 */
export const ${name}FormSchema = z.enum([${enumValues}])
  .meta({
    ui: {
      options: [
${optionsArray}
      ]
    }
  })

/**
 * Метки для значений enum ${name}
 */
export const ${name}Labels = {
${labelsObject}
} as const

/**
 * Тип значения enum
 */
export type ${name}Value = z.infer<typeof ${name}FormSchema>
`
}
