import type { DataModel, Enum } from '@zenstackhq/language/ast'
import { isDataModel, isEnum } from '@zenstackhq/language/ast'
import type { CliGeneratorContext } from '@zenstackhq/sdk'
import { mkdir, writeFile } from 'fs/promises'
import { dirname, join, resolve } from 'path'
import { extractEnumInfo, generateEnumCode } from './enum-generator.js'
import { collectEnumTranslations, collectModelTranslations, generateI18nFiles } from './i18n-generator.js'
import { extractModelInfo, generateModelCode } from './model-generator.js'
import type { I18nConfig } from './types.js'

/**
 * Получить путь вывода относительно схемы
 */
function getOutputPath(context: CliGeneratorContext): string {
  const output = (context.pluginOptions.output as string) ?? context.defaultOutputPath ?? './src/generated/form-schemas'
  const schemaDir = dirname(context.schemaFile)
  return resolve(schemaDir, output)
}

/**
 * Получить конфигурацию i18n из опций плагина
 */
function getI18nConfig(context: CliGeneratorContext): I18nConfig | null {
  const { pluginOptions } = context

  // i18n отключен по умолчанию
  const enabled = pluginOptions.i18n === true || pluginOptions.i18n === 'true'
  if (!enabled) {
    return null
  }

  // Парсим локали из строки "ru,en" или массива
  let locales: string[] = ['ru', 'en']
  if (typeof pluginOptions.locales === 'string') {
    locales = pluginOptions.locales.split(',').map((l) => l.trim())
  } else if (Array.isArray(pluginOptions.locales)) {
    locales = pluginOptions.locales as string[]
  }

  return {
    enabled: true,
    output: (pluginOptions.i18nOutput as string) ?? './messages/form-schemas',
    defaultLocale: (pluginOptions.defaultLocale as string) ?? 'ru',
    locales,
  }
}

/**
 * Записать файл, создав директории при необходимости
 */
async function writeFileWithDir(filePath: string, content: string): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf-8')
}

/**
 * Сгенерировать index.ts с реэкспортами
 */
function generateIndexCode(enumNames: string[], modelNames: string[]): string {
  const exports: string[] = []

  // Экспорты enum'ов
  for (const name of enumNames) {
    exports.push(`export * from './enums/${name}.form'`)
  }

  // Экспорты моделей
  for (const name of modelNames) {
    exports.push(`export * from './${name}.form'`)
  }

  return `// AUTO-GENERATED by @lena/zenstack-form-plugin
// DO NOT EDIT MANUALLY

${exports.join('\n')}
`
}

/**
 * Основная функция генерации
 */
export async function generate(context: CliGeneratorContext): Promise<void> {
  const outputDir = getOutputPath(context)
  const { model } = context
  const enumsDir = join(outputDir, 'enums')
  const schemaDir = dirname(context.schemaFile)

  // Получаем конфигурацию i18n
  const i18nConfig = getI18nConfig(context)

  // Собираем все enum'ы и модели из AST
  const enums: Enum[] = []
  const models: DataModel[] = []

  for (const decl of model.declarations) {
    if (isEnum(decl)) {
      enums.push(decl)
    } else if (isDataModel(decl)) {
      models.push(decl)
    }
  }

  // Создаём set имён enum'ов для проверки типов полей
  const enumNames = new Set(enums.map((e) => e.name))

  // Извлекаем информацию для генерации
  const enumInfos = enums.map((e) => extractEnumInfo(e))
  const modelInfos = models.map((m) => extractModelInfo(m, enumNames))

  // Генерируем enum файлы
  for (const enumInfo of enumInfos) {
    const code = generateEnumCode(enumInfo, i18nConfig)
    const filePath = join(enumsDir, `${enumInfo.name}.form.ts`)
    await writeFileWithDir(filePath, code)
  }

  // Генерируем model файлы
  for (const modelInfo of modelInfos) {
    const code = generateModelCode(modelInfo, enumNames, i18nConfig)
    const filePath = join(outputDir, `${modelInfo.name}.form.ts`)
    await writeFileWithDir(filePath, code)
  }

  // Генерируем index.ts
  const indexCode = generateIndexCode(
    enums.map((e) => e.name),
    models.map((m) => m.name)
  )
  await writeFileWithDir(join(outputDir, 'index.ts'), indexCode)

  // Генерируем i18n файлы если включено
  if (i18nConfig) {
    const translations = {
      models: collectModelTranslations(modelInfos),
      enums: collectEnumTranslations(enumInfos),
    }
    await generateI18nFiles(translations, i18nConfig, schemaDir)
  }

  // eslint-disable-next-line no-console
  console.log(`[zenstack-form-plugin] Generated ${enums.length} enum(s) and ${models.length} model(s)`)
}
