import type { DataModel, Enum } from '@zenstackhq/language/ast'
import { isDataModel, isEnum } from '@zenstackhq/language/ast'
import type { CliGeneratorContext } from '@zenstackhq/sdk'
import { mkdir, writeFile } from 'fs/promises'
import { dirname, join, resolve } from 'path'
import { extractEnumInfo, generateEnumCode } from './enum-generator.js'
import { collectEnumTranslations, collectModelTranslations, generateI18nFiles } from './i18n-generator.js'
import { extractModelInfo, generateModelCode } from './model-generator.js'
import type { I18nConfig } from './types.js'

/**
 * Get output path relative to schema file.
 */
function getOutputPath(context: CliGeneratorContext): string {
  const output = (context.pluginOptions.output as string) ?? context.defaultOutputPath ?? './src/generated/form-schemas'
  const schemaDir = dirname(context.schemaFile)
  return resolve(schemaDir, output)
}

/**
 * Parse i18n configuration from plugin options.
 */
function getI18nConfig(context: CliGeneratorContext): I18nConfig | null {
  const { pluginOptions } = context

  // i18n is disabled by default
  const enabled = pluginOptions.i18n === true || pluginOptions.i18n === 'true'
  if (!enabled) {
    return null
  }

  // Parse locales from "en,ru" string or array
  let locales: string[] = ['en']
  if (typeof pluginOptions.locales === 'string') {
    locales = pluginOptions.locales.split(',').map((l) => l.trim())
  } else if (Array.isArray(pluginOptions.locales)) {
    locales = pluginOptions.locales as string[]
  }

  return {
    enabled: true,
    output: (pluginOptions.i18nOutput as string) ?? './messages/form-schemas',
    defaultLocale: (pluginOptions.defaultLocale as string) ?? 'en',
    locales,
    validationTranslationsPath: pluginOptions.validationTranslationsPath as string | undefined,
  }
}

/**
 * Write a file, creating directories as needed.
 */
async function writeFileWithDir(filePath: string, content: string): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf-8')
}

/**
 * Generate index.ts with re-exports.
 */
function generateIndexCode(enumNames: string[], modelNames: string[]): string {
  const exports: string[] = []

  for (const name of enumNames) {
    exports.push(`export * from './enums/${name}.form'`)
  }

  for (const name of modelNames) {
    exports.push(`export * from './${name}.form'`)
  }

  return `// AUTO-GENERATED by @letar/zenstack-form-plugin
// DO NOT EDIT MANUALLY

${exports.join('\n')}
`
}

/**
 * Main generation function.
 */
export async function generate(context: CliGeneratorContext): Promise<void> {
  const outputDir = getOutputPath(context)
  const { model } = context
  const enumsDir = join(outputDir, 'enums')
  const schemaDir = dirname(context.schemaFile)

  // Get i18n configuration
  const i18nConfig = getI18nConfig(context)

  // Collect all enums and models from AST
  const enums: Enum[] = []
  const models: DataModel[] = []

  for (const decl of model.declarations) {
    if (isEnum(decl)) {
      enums.push(decl)
    } else if (isDataModel(decl)) {
      models.push(decl)
    }
  }

  // Build enum name set for field type checking
  const enumNames = new Set(enums.map((e) => e.name))

  // Extract information for generation
  const enumInfos = enums.map((e) => extractEnumInfo(e))
  const modelInfos = models.map((m) => extractModelInfo(m, enumNames))

  // Generate enum files
  for (const enumInfo of enumInfos) {
    const code = generateEnumCode(enumInfo, i18nConfig)
    const filePath = join(enumsDir, `${enumInfo.name}.form.ts`)
    await writeFileWithDir(filePath, code)
  }

  // Generate model files
  for (const modelInfo of modelInfos) {
    const code = generateModelCode(modelInfo, enumNames, i18nConfig)
    const filePath = join(outputDir, `${modelInfo.name}.form.ts`)
    await writeFileWithDir(filePath, code)
  }

  // Generate index.ts
  const indexCode = generateIndexCode(
    enums.map((e) => e.name),
    models.map((m) => m.name),
  )
  await writeFileWithDir(join(outputDir, 'index.ts'), indexCode)

  // Generate i18n files if enabled
  if (i18nConfig) {
    const translations = {
      models: collectModelTranslations(modelInfos),
      enums: collectEnumTranslations(enumInfos),
    }
    await generateI18nFiles(translations, i18nConfig, schemaDir)
  }

  // eslint-disable-next-line no-console
  console.log(`[zenstack-form-plugin] Generated ${enums.length} enum(s) and ${models.length} model(s)`)
}
